#pull_request_title: 'docs(i18n): New Crowdin updates'
#pull_request_labels:
#  - docs
#  - translations
#commit_message: 'docs(i18n): New translations for %original_file_name% (%language%)'
#append_commit_message: false
#files:
#  - source: /i18n/*.ts
#    ignore:
##      - /docs/%locale%  # translated files
##      - /docs/blog/**/* # blog posts
#    translation: /docs/%two_letters_code%/**/%original_file_name%
project_id: 792142
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."
branch: main
preserve_hierarchy: true

files:
  - source: "/i18n/*.ts"
    translation: "/i18n_translations/%locale%/%original_file_name%"

  - source: "/help/**/*.md"
    translation: "/help_translations/%locale%/**/%original_file_name%"