# mkdocs.yml
site_name: Ma Documentation Multilingue
theme:
  name: material
  language: fr  # Langue par défaut
  palette:
    scheme: default
  features:
    - content.code.copy

docs_dir: help  # Spécifie explicitement le répertoire des fichiers de documentation

plugins:
  - search
  - i18n:
      default_language: fr
      languages:
        fr
        en
      default_language_only: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Accueil:
      - fr: index.fr.md
      - en: index.en.md
  - Premiers pas:
      - fr: getting_started.fr.md
      - en: getting_started.en.md