# mkdocs.yml
site_name: Ma Documentation Multilingue
theme:
  name: readthedocs
  language: fr  # Langue par défaut
  palette:
    scheme: default
  features:
    - content.code.copy

docs_dir: help  # Spécifie explicitement le répertoire des fichiers de documentation

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Accueil:
      - fr: fr/index.fr.md
      - en: en/index.en.md
  - Premiers pas:
      - fr: en/getting_started.fr.md
      - en: en/getting_started.en.md