# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OSMandLinkerDialog
                                 A QGIS plugin
 Import tracks, AV notes from OSMand
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-10
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sylvain Théry - UMR 5281 ART-Dev
        email                : sylvain.thery@cnrs.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import datetime as dt
from PyQt5.QtWidgets import QTableWidgetItem
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'osmand_linker_dialog_avnotes.ui'))


class OSMandLinkerDialogAVnotes(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(OSMandLinkerDialogAVnotes, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.tableWidgetAVNotes.setColumnCount(3)
        columns = [self.tr("Name"), self.tr("Size"), self.tr("Last Modified")]
        self.tableWidgetAVNotes.setHorizontalHeaderLabels(columns)
        self.tableWidgetAVNotes.setSortingEnabled(True)
        self.getStatistic("/tmp/")
        # for i in range(1,10):
        #     self.addTableRow([f"a{i}", f"b", "c"])


    # def getStatistic(self, path):
    #     listFiles = os.listdir(path)
    #     for f in listFiles:
    #         p = os.path.join(path, f)
    #         st = os.stat(p)
    #         name, size, last = f, str(os.path.getsize(p)), str(st.st_mtime)
    #         yield name, size, last
    def getStatistic(self, path):
        listFiles = os.listdir(path)
        for f in listFiles:
            p = os.path.join(path, f)
            st = os.stat(p)
            self.addTableRow([f, self.human_size(os.path.getsize(p)), str(dt.datetime.fromtimestamp(st.st_mtime))[:-7]])

    def addTableRow(self, row_data):
        row = self.tableWidgetAVNotes.rowCount()
        self.tableWidgetAVNotes.setRowCount(row + 1)
        col = 0
        for item in row_data:
            cell = QTableWidgetItem(str(item))
            self.tableWidgetAVNotes.setItem(row, col, cell)
            col += 1

    def human_size(self, bytes, units=[' bytes', ' KB', ' MB', ' GB', ' TB', ' PB', ' EB']):
        """ Returns a human readable string representation of bytes """
        return str(bytes) + units[0] if bytes < 1024 else self.human_size(bytes >> 10, units[1:])

