# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OSMandLinkerDialog
                                 A QGIS plugin
 Import tracks, AV notes from OSMand
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-10
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sylvain Théry - UMR 5281 ART-Dev
        email                : sylvain.thery@cnrs.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os

from qgis import processing


def import_gpx_track_file(self, file):
    """

    """
    file_name = f'{self.osmand_root_path}/tracks/rec/{file}'
    print(file_name)
    names = ["waypoint", "route", "track", "route_point", "track_point"]

    for name in names:
        self.iface.addVectorLayer(file_name + "?type=" + name, name, "gpx")
        processing.run("native:savefeatures", {
            'INPUT': f'gpx://{file_name}?type={name}',
            'OUTPUT': self.dest_gpkg,
            'LAYER_NAME': name, 'DATASOURCE_OPTIONS': '', 'LAYER_OPTIONS': ''})

    pass