# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OsmAnd bridge
                                 A QGIS plugin
 Import tracks, favorites, itinerary and AV notes from OsmAnd
 Generated by Plugin Builder: https://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-10
        git sha              : $Format:%H$
        copyright            : (C) 2022-2026 by Sylvain Théry - UMR 5281 ART-Dev
        email                : sylvain.thery@cnrs.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import datetime as dt
import glob
import os
import platform
import subprocess
import tempfile

from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtGui import QGuiApplication
from qgis.PyQt.QtWidgets import QTableWidgetItem, QDialogButtonBox, QTableWidget, QCheckBox, QLabel, QPushButton, \
    QRadioButton, QComboBox, QMessageBox, QVBoxLayout
from qgis.gui import QgsFileWidget

from .OsmAnd_bridge_settings_management import msgbox_setting

# Import MTP libraries depending on OS.
# Linux  : unified KIO/gvfs backend (mtp_access_kio_gvfs).
# Windows: native WPD COM backend (mtp_access_windows) — no third-party MTP lib.
MTPClient = None
if platform.system() == 'Linux':
    try:
        from .extra_packages.mtp_access_kio_gvfs.mtp_access_kio_gvfs import MTPClient
    except Exception as _mtp_import_error:
        MTPClient = None
elif platform.system() == 'Windows':
    try:
        from .extra_packages.mtp_access_windows.mtp_access_windows import MTPClient
    except Exception as _mtp_import_error:
        MTPClient = None
        # Log the actual error so the cause is visible in the QGIS message log.
        # Common causes: comtypes not installed in QGIS's Python environment,
        # wrong extra_packages path, or a missing Windows DLL.
        try:
            from qgis.core import QgsMessageLog, Qgis
            QgsMessageLog.logMessage(
                f"OsmAnd bridge: mtp_access_windows import failed — {type(_mtp_import_error).__name__}: {_mtp_import_error}",
                'OsmAnd bridge', level=Qgis.Warning)
        except Exception:
            pass  # QgsMessageLog not yet available at module import time

# Loads .ui
try:  # Qt5 — resource_suffix does not exist in Qt6
    FORM_CLASS, _ = uic.loadUiType(os.path.join(
        os.path.dirname(__file__), 'OsmAnd_bridge_import_dialog.ui'), resource_suffix='')
except Exception:  # Qt6
    FORM_CLASS, _ = uic.loadUiType(os.path.join(
        os.path.dirname(__file__), 'OsmAnd_bridge_import_dialog.ui'))


def _qmessagebox_set_icon_warning(msg):
    """Set Warning icon on a QMessageBox, compatible with Qt5 and Qt6."""
    try:  # Qt6 — enums namespaced
        msg.setIcon(QMessageBox.Icon.Warning)
    except AttributeError:  # Qt5
        msg.setIcon(QMessageBox.Warning)


def _qmessagebox_set_buttons_ok(msg):
    """Set Ok button on a QMessageBox, compatible with Qt5 and Qt6."""
    try:  # Qt6
        msg.setStandardButtons(QMessageBox.StandardButton.Ok)
    except AttributeError:  # Qt5
        msg.setStandardButtons(QMessageBox.Ok)


class OsmAndBridgeImportDialog(QtWidgets.QDialog, FORM_CLASS):
    """
    Class to manage import settings from OsmAnd directory or MTP device.
    """
    # Annotations for code editor completion
    buttonBox: QDialogButtonBox
    tW_tracks: QTableWidget
    QgsFW_osmand_root_path: QgsFileWidget
    QgsFW_dest_path: QgsFileWidget
    cB_favorites: QCheckBox
    cB_itinerary: QCheckBox
    cB_AVnotes: QCheckBox
    label: QLabel
    label_2: QLabel
    label_3: QLabel
    label_4: QLabel
    label_6: QLabel
    clearPB: QPushButton
    selectAllTracksPB: QPushButton
    rBdevice: QRadioButton
    rBdir: QRadioButton
    cBdeviceList: QComboBox
    qbRefresh: QPushButton
    qbGoMTP: QPushButton

    def __init__(self, parent=None):
        """
        Constructor.

        :param parent: Parent widget (None for top-level dialog).
        :type parent: QWidget or None
        """
        super(OsmAndBridgeImportDialog, self).__init__(parent)
        self.setupUi(self)

        # Make the scroll area resize with the dialog, keeping the buttonBox anchored at the bottom
        main_layout = QVBoxLayout(self)
        main_layout.setContentsMargins(0, 0, 0, 6)
        main_layout.setSpacing(6)
        main_layout.addWidget(self.scrollArea)
        main_layout.addWidget(self.buttonBox)
        self.setLayout(main_layout)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents.setMinimumSize(650, 634)

        self.plugin_name = 'OsmAnd bridge'

        # Manage table view of tracks
        self.tW_tracks.setColumnCount(3)
        columns = [self.tr("Name"), self.tr("Size"), self.tr("Last Modified")]
        self.tW_tracks.setHorizontalHeaderLabels(columns)
        self.tW_tracks.setSortingEnabled(True)
        self.tW_tracks.setRowCount(0)
        try:  # Qt6 — enums namespaced
            self.tW_tracks.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        except AttributeError:  # Qt5
            self.tW_tracks.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tW_tracks.selectionModel().selectionChanged.connect(self.enable_ok_button)

        # Input and output path widgets
        self.QgsFW_osmand_root_path.setStorageMode(QgsFileWidget.StorageMode.GetDirectory)
        self.QgsFW_osmand_root_path.fileChanged.connect(self.osmand_root_path_changed)
        self.QgsFW_dest_path.setStorageMode(QgsFileWidget.StorageMode.GetDirectory)
        self.QgsFW_dest_path.fileChanged.connect(self.destination_changed)

        # Checkboxes management
        for cBB in [self.cB_favorites, self.cB_itinerary, self.cB_AVnotes]:
            cBB.setEnabled(False)
            cBB.setChecked(False)
            cBB.stateChanged.connect(self.enable_ok_button)

        try:  # Qt6
            self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(False)
        except AttributeError:  # Qt5
            self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setEnabled(False)

        # Clear tracks selection button
        try:  # Qt6
            icon = self.style().standardIcon(QtWidgets.QStyle.StandardPixmap.SP_DialogCloseButton)
        except AttributeError:  # Qt5
            icon = self.style().standardIcon(QtWidgets.QStyle.SP_DialogCloseButton)
        self.clearPB.setIcon(icon)
        self.clearPB.setEnabled(False)
        self.clearPB.clicked.connect(self.clear_tracks_selection)

        # Select all tracks button
        try:  # Qt6
            icon = self.style().standardIcon(QtWidgets.QStyle.StandardPixmap.SP_DialogYesButton)
        except AttributeError:  # Qt5
            icon = self.style().standardIcon(QtWidgets.QStyle.SP_DialogYesButton)
        self.selectAllTracksPB.setIcon(icon)
        self.selectAllTracksPB.setEnabled(False)
        self.selectAllTracksPB.clicked.connect(self.select_all_tracks)

        # Radio buttons to switch between device and directory mode
        self.rBdir.toggled.connect(self.on_radio_button_toggled)
        self.rBdevice.toggled.connect(self.on_radio_button_toggled)
        self.cBdeviceList.hide()
        self.QgsFW_osmand_root_path.hide()
        self.label.hide()
        self.qbRefresh.hide()
        self.qbRefresh.clicked.connect(self.list_MTP_Devices)
        self.qbGoMTP.hide()
        self.qbGoMTP.clicked.connect(self.search_copy_osmand_file_from_device)
        self.qbGoMTP.setEnabled(False)
        try:  # Qt6
            icon = self.style().standardIcon(QtWidgets.QStyle.StandardPixmap.SP_BrowserReload)
        except AttributeError:  # Qt5
            icon = self.style().standardIcon(QtWidgets.QStyle.SP_BrowserReload)
        self.qbRefresh.setIcon(icon)
        try:  # Qt6
            icon = self.style().standardIcon(QtWidgets.QStyle.StandardPixmap.SP_DialogOkButton)
        except AttributeError:  # Qt5
            icon = self.style().standardIcon(QtWidgets.QStyle.SP_DialogOkButton)
        self.qbGoMTP.setIcon(icon)

        # Path to the settings JSON file
        self.PARAM_FILE = f"{os.path.dirname(__file__)}/settings.json"

        # Strings reused across methods
        self.title_cant_connect = self.tr("Can't connect to device...")
        self.message_cant_connect = self.tr(
            "Check that it is properly connected and unlocked.\n Try unplugging "
            "and replugging it. Consider disabling ADB.")
        self.title_no_device_found = self.tr('No device found!')
        self.message_no_device_found = self.tr("Check that your device is properly connected and unlocked. Consider disabling ADB.\n"
                                               "You can press left button to refresh devices list or to restart QGIS.")

        # Windows: MTPClient is imported from mtp_access_windows (WPD COM API).
        # comtypes must be available; if not, the device radio button is disabled.
        if platform.system() == 'Windows':
            if MTPClient is None:
                self.rBdevice.setEnabled(False)
                QgsMessageLog.logMessage(
                    "mtp_access_windows could not be imported (comtypes missing?). "
                    "MTP device access disabled.",
                    self.plugin_name, level=Qgis.Warning)
            else:
                self.rBdevice.setEnabled(True)

        # macOS: MacDroid app is required
        self.APP_NAME = "MacDroid"
        self.APP_PATH = f"/Applications/{self.APP_NAME}.app"

    # ------------------------------------------------------------------
    # MTP device listing
    # ------------------------------------------------------------------

    def list_MTP_Devices(self):
        """
        List MTP devices connected to the system and populate the device combo-box.

        - Linux  : uses MTPClient (KIO or gvfs backend, auto-detected).
        - Windows: uses comtypes / win_access.
        - macOS  : uses MacDroid's virtual filesystem under ~/.AFTVolumes.
        """
        self.clear_UI_items()
        self.qbGoMTP.setEnabled(False)

        if platform.system() == 'Linux':
            # ----------------------------------------------------------------
            # Linux — KIO/gvfs backend via MTPClient
            # ----------------------------------------------------------------
            if MTPClient is None:
                QgsMessageLog.logMessage(
                    "MTPClient could not be imported. Check mtp_access_kio_gvfs installation.",
                    self.plugin_name, level=Qgis.Critical)
                QMessageBox.warning(self, self.title_no_device_found,
                                    "MTP backend not available. Check plugin installation.")
                return

            try:
                client = MTPClient()
            except RuntimeError as e:
                # No backend detected (kiod5 / gvfsd-mtp not running)
                QgsMessageLog.logMessage(str(e), self.plugin_name, level=Qgis.Warning)
                QMessageBox.warning(self, self.title_no_device_found, self.message_no_device_found)
                return

            devices = client.list_devices()

            if not devices:
                QMessageBox.warning(self, self.title_no_device_found, self.message_no_device_found)
                return

            for device in devices:
                # For KIO the device is a short name (e.g. "Smini");
                # for gvfs it is a full mount-point path.
                # We display only the last path component for gvfs to keep the UI readable.
                display_name = client.get_display_name(device)
                self.cBdeviceList.addItem(display_name, userData=device)

            self.qbGoMTP.setEnabled(True)

        elif platform.system() == 'Windows':
            # Windows — WPD COM backend via MTPClient (mtp_access_windows)
            if MTPClient is None:
                QgsMessageLog.logMessage(
                    "MTPClient not available on Windows. Check comtypes installation.",
                    self.plugin_name, level=Qgis.Critical)
                QMessageBox.warning(self, self.title_no_device_found,
                                    "MTP backend not available. Check plugin installation.")
                return

            try:
                client = MTPClient()
            except RuntimeError as e:
                QgsMessageLog.logMessage(str(e), self.plugin_name, level=Qgis.Warning)
                QMessageBox.warning(self, self.title_no_device_found, self.message_no_device_found)
                return

            devices = client.list_devices()
            if not devices:
                QMessageBox.warning(self, self.title_no_device_found, self.message_no_device_found)
                return

            for device in devices:
                display_name = client.get_display_name(device)
                self.cBdeviceList.addItem(display_name, userData=device)

            self.qbGoMTP.setEnabled(True)

        elif platform.system() == 'Darwin':
            if self.is_macdroid_installed():
                if not self.is_macdroid_running():
                    self.launch_macdroid()

                path = os.path.join(os.path.expanduser("~"), ".AFTVolumes")

                try:
                    for subdir in os.listdir(path):
                        if os.path.isdir(os.path.join(path, subdir)):
                            self.cBdeviceList.addItem(subdir)
                except Exception:
                    pass

                if self.cBdeviceList.count() > 0:
                    self.qbGoMTP.setEnabled(True)
                else:
                    QMessageBox.warning(self, self.title_no_device_found, self.message_no_device_found)
            else:
                self.rBdir.setChecked(True)
                self.rBdevice.setEnabled(False)
                self.on_radio_button_toggled()
                title = self.tr("Warning")
                message = self.tr(
                    "This plugin needs MacDroid (even Free version) to access MTP Device. Please consider installing it."
                    "See <a href='https://www.macdroid.app/fr/downloads/'>https://www.macdroid.app/fr/downloads</a>")
                QMessageBox.warning(None, title, message)

    # ------------------------------------------------------------------
    # MTP file search & copy
    # ------------------------------------------------------------------

    def search_copy_osmand_file_from_device(self):
        """
        Search OsmAnd files on the selected MTP device and copy them to a
        temporary directory so the rest of the plugin can process them normally.

        - Linux  : uses MTPClient.copy_from_device() (KIO/gvfs backend).
        - Windows: uses comtypes / win_access (unchanged).
        - macOS  : MacDroid mounts the device as a real filesystem; no copy needed.
        """
        setting_name = "hide_duration_message"
        title = self.tr("Warning")
        mtpy_msg = self.tr(", especially under GNU/Linux :(") if platform.system() == 'Linux' else ''
        message = self.tr(f"Be patient! \nThis operation can take several minutes{mtpy_msg}.\nIn rare cases, "
                          f"it can cause Qgis to crash.")
        msgbox_setting(self, setting_name, title, message)

        try:  # Qt6
            QGuiApplication.setOverrideCursor(Qt.CursorShape.WaitCursor)
        except AttributeError:  # Qt5
            QGuiApplication.setOverrideCursor(Qt.WaitCursor)

        # Sub-paths relative to the OsmAnd root that we want to retrieve.
        # Each entry maps device relative path → local relative path under tmp_dir_name.
        # They are identical here but kept separate for clarity.
        items_list = ['/avnotes/', '/tracks/rec/', '/favorites/', '/itinerary.gpx']

        # Possible OsmAnd root paths on the Android device storage
        potential_paths = [
            '/Android/data/net.osmand/files',
            '/Android/data/net.osmand.plus/files',
            '/Android/media/net.osmand/files',
            '/Android/media/net.osmand.plus/files',
            '/Android/obb/net.osmand/files',
            '/Android/obb/net.osmand.plus/files',
        ]

        if platform.system() != "Darwin":
            # Create a temporary directory; sub-directories are created on demand
            # by copy_from_device_to_exact, except tracks/rec which needs its
            # parent created first.
            # Store the TemporaryDirectory object in self so it is NOT
            # garbage-collected before the copy completes.  Without this,
            # Python immediately destroys the object (and the directory)
            # because no reference is kept.
            self._tmp_dir = tempfile.TemporaryDirectory()
            tmp_dir_name  = self._tmp_dir.name
            os.makedirs(tmp_dir_name + '/tracks/rec', exist_ok=True)

        # ==============================================================
        # Linux — KIO/gvfs via MTPClient
        # ==============================================================
        if platform.system() == 'Linux':
            if MTPClient is None:
                QGuiApplication.restoreOverrideCursor()
                QMessageBox.warning(self, self.title_cant_connect,
                                    "MTP backend not available. Check plugin installation.")
                return

            try:
                client = MTPClient()
            except RuntimeError as e:
                QGuiApplication.restoreOverrideCursor()
                QgsMessageLog.logMessage(str(e), self.plugin_name, level=Qgis.Critical)
                QMessageBox.warning(self, self.title_cant_connect, self.message_cant_connect)
                return

            # Retrieve the device identifier stored as userData in the combo-box.
            # KIO: short name (e.g. "Smini"); gvfs: full mount-point path.
            selected_device = self.cBdeviceList.currentData()
            if selected_device is None:
                selected_device = self.cBdeviceList.currentText()

            # Identify the OsmAnd root path on the device by iterating over
            # storage roots (e.g. "Espace de stockage interne partagé") and
            # candidate sub-paths. We confirm a match by checking that the
            # listed contents include at least one known OsmAnd marker.
            osmand_root_on_device = None
            osmand_markers = {'tracks', 'favorites', 'avnotes', 'itinerary.gpx', 'voice'}
            for storage_root in client.list_folder(selected_device, ''):
                for path in potential_paths:
                    probe = f"{storage_root}/{path.lstrip('/')}"
                    try:
                        contents = client.list_folder(selected_device, probe)
                        if contents and osmand_markers.intersection(set(contents)):
                            osmand_root_on_device = probe
                            QgsMessageLog.logMessage(
                                f"Linux MTP: OsmAnd data found at {osmand_root_on_device}",
                                self.plugin_name, level=Qgis.Info)
                            break
                    except Exception:
                        pass
                if osmand_root_on_device:
                    break

            if not osmand_root_on_device:
                QGuiApplication.restoreOverrideCursor()
                msg = QMessageBox()
                msg.setWindowTitle(self.tr("No files found"))
                msg.setText(self.tr(
                    f"OsmAnd files could not be found on {selected_device}. "
                    "Check that MTP transport is selected on it. "
                    "As a last resort, copy files to your hard disk and import them "
                    "into QGIS from the local directory."))
                _qmessagebox_set_icon_warning(msg)
                _qmessagebox_set_buttons_ok(msg)
                msg.exec()
                return

            # Copy each OsmAnd item to the exact local path expected by
            # osmand_root_path_changed:
            #   avnotes/      → tmp/avnotes/<files>
            #   tracks/rec/   → tmp/tracks/rec/<gpx files>
            #   favorites/    → tmp/favorites/<gpx files>
            #   itinerary.gpx → tmp/itinerary.gpx
            for item in items_list:
                src_path = f"{osmand_root_on_device}{item}".rstrip('/')
                dst_exact = (tmp_dir_name + item).rstrip('/')
                try:
                    client.copy_from_device_to_exact(selected_device, src_path, dst_exact)
                    QgsMessageLog.logMessage(
                        f"Linux MTP: copied {src_path} -> {dst_exact}",
                        self.plugin_name, level=Qgis.Info)
                except Exception as e:
                    QgsMessageLog.logMessage(
                        f"Linux MTP: could not copy {src_path}: {e}",
                        self.plugin_name, level=Qgis.Warning)

        # ==============================================================
        # Windows — WPD COM backend via MTPClient (mtp_access_windows)
        # Uses the same logic as the Linux section.
        # ==============================================================
        elif platform.system() == 'Windows':
            if MTPClient is None:
                QGuiApplication.restoreOverrideCursor()
                QMessageBox.warning(self, self.title_cant_connect,
                                    "MTP backend not available. Check plugin installation.")
                return

            try:
                client = MTPClient()
            except RuntimeError as e:
                QGuiApplication.restoreOverrideCursor()
                QgsMessageLog.logMessage(str(e), self.plugin_name, level=Qgis.Critical)
                QMessageBox.warning(self, self.title_cant_connect, self.message_cant_connect)
                return

            selected_device = self.cBdeviceList.currentData()
            if selected_device is None:
                selected_device = self.cBdeviceList.currentText()

            # Find the OsmAnd root path by checking storage roots against
            # known candidate paths and confirming with OsmAnd marker files.
            osmand_root_on_device = None
            osmand_markers = {'tracks', 'favorites', 'avnotes', 'itinerary.gpx', 'voice'}
            for storage_root in client.list_folder(selected_device, ''):
                for path in potential_paths:
                    probe = f"{storage_root}/{path.lstrip('/')}"
                    try:
                        contents = client.list_folder(selected_device, probe)
                        if contents and osmand_markers.intersection(set(contents)):
                            osmand_root_on_device = probe
                            QgsMessageLog.logMessage(
                                f"Windows MTP: OsmAnd data found at {osmand_root_on_device}",
                                self.plugin_name, level=Qgis.Info)
                            break
                    except Exception:
                        pass
                if osmand_root_on_device:
                    break

            if not osmand_root_on_device:
                QGuiApplication.restoreOverrideCursor()
                msg = QMessageBox()
                msg.setWindowTitle(self.tr("No files found"))
                msg.setText(self.tr(
                    f"OsmAnd files could not be found on {selected_device}. "
                    "Check that MTP transport is selected on it. "
                    "As a last resort, copy files to your hard disk and import them "
                    "into QGIS from the local directory."))
                _qmessagebox_set_icon_warning(msg)
                _qmessagebox_set_buttons_ok(msg)
                msg.exec()
                return

            # Copy each OsmAnd item to the exact local path expected by
            # osmand_root_path_changed (same logic as Linux).
            for item in items_list:
                src_path = f"{osmand_root_on_device}{item}".rstrip('/')
                dst_exact = (tmp_dir_name + item).rstrip('/')
                try:
                    client.copy_from_device_to_exact(selected_device, src_path, dst_exact)
                    QgsMessageLog.logMessage(
                        f"Windows MTP: copied {src_path} -> {dst_exact}",
                        self.plugin_name, level=Qgis.Info)
                except Exception as e:
                    QgsMessageLog.logMessage(
                        f"Windows MTP: could not copy {src_path}: {e}",
                        self.plugin_name, level=Qgis.Warning)

        # ==============================================================
        # macOS — MacDroid mounts device as filesystem, no copy needed
        # ==============================================================
        elif platform.system() == 'Darwin':
            root_path = os.path.join(os.path.expanduser("~"), ".AFTVolumes", self.cBdeviceList.currentText())
            found = False
            for root, subdir, _ in os.walk(root_path):
                for dirname in subdir:
                    if dirname.startswith("net.osmand"):
                        tmp_dir_name = os.path.join(root, dirname)
                        found = True
                        break
                if found:
                    tmp_dir_name = tmp_dir_name + '/files/'
                    break

            if not found:
                QGuiApplication.restoreOverrideCursor()
                msg = QMessageBox()
                msg.setWindowTitle(self.tr("No files found"))
                msg.setText(
                    self.tr(f"OsmAnd files could not be found on {self.cBdeviceList.currentText()}. "
                            "Try copying the files to your hard disk and importing them into QGIS from the "
                            "local directory."))
                _qmessagebox_set_icon_warning(msg)
                _qmessagebox_set_buttons_ok(msg)
                msg.exec()
                return

        self.QgsFW_osmand_root_path.setFilePath(tmp_dir_name)
        QGuiApplication.restoreOverrideCursor()

    # ------------------------------------------------------------------
    # UI helpers
    # ------------------------------------------------------------------

    def on_radio_button_toggled(self):
        self.label.show()
        self.clear_UI_items()
        if self.rBdir.isChecked():
            self.QgsFW_osmand_root_path.setFilePath('')
            self.QgsFW_osmand_root_path.show()
            self.cBdeviceList.hide()
            self.qbRefresh.hide()
            self.qbGoMTP.hide()
            self.label.setText(self.tr('<html><head/><body><p><span style=" font-weight:600;">Select the OSMand'
                                       ' \'file\' directory on you computer:</span></p></body></html>'))
        elif self.rBdevice.isChecked():
            self.QgsFW_osmand_root_path.hide()
            self.QgsFW_osmand_root_path.setFilePath('')
            self.cBdeviceList.show()
            self.qbRefresh.show()
            self.qbGoMTP.show()
            self.label.setText(self.tr(
                "<html><head/><body><p><span style=\" font-weight:600;\">"
                "Select your device and press the right button to search for OsmAnd files.<br>"
                "You can use the left button to refresh devices list."
                "</span></p></body></html>"))
            self.list_MTP_Devices()

    def clear_UI_items(self):
        """Clear all UI items (device list, track table, path widgets, checkboxes)."""
        self.cBdeviceList.clear()
        self.tW_tracks.clearContents()
        self.tW_tracks.setRowCount(0)
        self.QgsFW_osmand_root_path.setFilePath('')
        for item in [self.cB_itinerary, self.cB_favorites, self.cB_AVnotes]:
            item.setEnabled(False)
            item.setChecked(False)

    def is_macdroid_installed(self):
        return os.path.exists(self.APP_PATH)

    def is_macdroid_running(self):
        try:
            result = subprocess.run(
                ["pgrep", "-fx", f"/Applications/{self.APP_NAME}.app/Contents/MacOS/{self.APP_NAME}"],
                capture_output=True, text=True)
            return result.returncode == 0
        except Exception as e:
            QgsMessageLog.logMessage(f"Issue when trying to see if macDroid is launched {e}",
                                     self.plugin_name, level=Qgis.Critical)
            return False

    def launch_macdroid(self):
        try:
            subprocess.run(["open", "-a", self.APP_NAME], check=True)
        except subprocess.CalledProcessError:
            QgsMessageLog.logMessage("Failed to launch macDroid", self.plugin_name, level=Qgis.Critical)

    def clear_tracks_selection(self) -> None:
        self.tW_tracks.clearSelection()
        self.enable_ok_button()

    def select_all_tracks(self):
        self.tW_tracks.selectAll()
        self.enable_ok_button()

    def destination_changed(self):
        if not os.path.exists(os.path.dirname(self.QgsFW_dest_path.filePath())):
            QgsMessageLog.logMessage(self.tr('Not a valid output file path.'), self.plugin_name, level=Qgis.Critical)
        self.enable_ok_button()

    def osmand_root_path_changed(self) -> None:
        """Called when the source directory path changes."""
        self.tW_tracks.clearContents()
        self.tW_tracks.setRowCount(0)
        self.clearPB.setEnabled(False)
        self.selectAllTracksPB.setEnabled(False)

        if not os.path.isdir(self.QgsFW_osmand_root_path.filePath()):
            QgsMessageLog.logMessage(self.tr('Not a valid directory.'), self.plugin_name, level=Qgis.Critical)
        else:
            # Tracks table
            try:
                if not os.path.isdir(f'{self.QgsFW_osmand_root_path.filePath()}/tracks/rec/'):
                    QgsMessageLog.logMessage(self.tr('No valid OsmAnd tracks path.'), self.plugin_name,
                                             level=Qgis.Critical)
                else:
                    pattern = f'{self.QgsFW_osmand_root_path.filePath()}/tracks/rec/*.gpx'
                    if len(glob.glob(pattern)) >= 0:
                        self.get_gpx_file_information(pattern)
                        self.tW_tracks.setEnabled(True)
                        self.tW_tracks.resizeColumnsToContents()
                        self.clearPB.setEnabled(True)
                        self.selectAllTracksPB.setEnabled(True)
                        self.select_all_tracks()
                        QgsMessageLog.logMessage(self.tr('Found gpx file(s) to import.'), self.plugin_name,
                                                 level=Qgis.Info)
            except Exception:
                QgsMessageLog.logMessage(self.tr('No gpx file to import.'), self.plugin_name, level=Qgis.Warning)

            # Favorites checkbox — file is under favorites/favorites.gpx
            try:
                with open(f'{self.QgsFW_osmand_root_path.filePath()}/favorites/favorites.gpx'):
                    QgsMessageLog.logMessage(self.tr('Found favorites.gpx.'), self.plugin_name, level=Qgis.Info)
                    self.cB_favorites.setEnabled(True)
                    self.cB_favorites.setChecked(True)
            except IOError:
                QgsMessageLog.logMessage(self.tr('No favorites found.'), self.plugin_name, level=Qgis.Warning)
                self.cB_favorites.setEnabled(False)
                self.cB_favorites.setChecked(False)

            # Itinerary checkbox
            try:
                with open(f'{self.QgsFW_osmand_root_path.filePath()}/itinerary.gpx'):
                    QgsMessageLog.logMessage(self.tr('Found ./itinerary.gpx.'), self.plugin_name, level=Qgis.Info)
                    self.cB_itinerary.setEnabled(True)
                    self.cB_itinerary.setChecked(True)
            except IOError:
                QgsMessageLog.logMessage(self.tr('./itinerary.gpx not found.'), self.plugin_name, level=Qgis.Warning)
                self.cB_itinerary.setEnabled(False)
                self.cB_itinerary.setChecked(False)

            # AVnotes checkbox
            try:
                if not os.path.isdir(f'{self.QgsFW_osmand_root_path.filePath()}/avnotes/'):
                    QgsMessageLog.logMessage(self.tr('No valid OsmAnd avnotes path.'), self.plugin_name,
                                             level=Qgis.Critical)
                    self.cB_AVnotes.setEnabled(False)
                    self.cB_AVnotes.setChecked(False)
                else:
                    avnotes_path = self.QgsFW_osmand_root_path.filePath()
                    if len(glob.glob(f'{avnotes_path}/avnotes/*.3gp')) + \
                            len(glob.glob(f'{avnotes_path}/avnotes/*.jpg')) + \
                            len(glob.glob(f'{avnotes_path}/avnotes/*.mp4')) > 0:
                        self.cB_AVnotes.setEnabled(True)
                        self.cB_AVnotes.setChecked(True)
                        QgsMessageLog.logMessage(self.tr('Found OsmAnd AV note(s) to import.'), self.plugin_name,
                                                 level=Qgis.Info)
            except Exception:
                QgsMessageLog.logMessage(self.tr('No AV note file(s) to import.'), self.plugin_name,
                                         level=Qgis.Warning)

        self.enable_ok_button()

    def get_gpx_file_information(self, pattern: str) -> None:
        """
        List files matching *pattern* and populate the track table.

        :param pattern: A glob pattern with directory (e.g. '/home/user/test/*.gpx').
        :type pattern: str
        """
        for f in glob.glob(pattern):
            st = os.stat(f)
            self.add_gpx_file_table_row([os.path.basename(f),
                                         self.human_readable_filesize(os.path.getsize(f)),
                                         str(dt.datetime.fromtimestamp(st.st_mtime))])

    def add_gpx_file_table_row(self, row_data) -> None:
        row = self.tW_tracks.rowCount()
        self.tW_tracks.setRowCount(row + 1)
        col = 0
        for item in row_data:
            cell = QTableWidgetItem(str(item))
            self.tW_tracks.setItem(row, col, cell)
            col += 1

    def human_readable_filesize(self, bytes: int,
                                units=[' bytes', ' KB', ' MB', ' GB', ' TB', ' PB', ' EB']) -> str:
        return str(bytes) + units[0] if bytes < 1024 else self.human_readable_filesize(bytes >> 10, units[1:])

    def enable_ok_button(self):
        flag = False
        try:
            if os.path.isdir(os.path.dirname(self.QgsFW_osmand_root_path.filePath())):
                if os.path.isdir(self.QgsFW_dest_path.filePath()):
                    if self.cB_AVnotes.isChecked() or self.cB_favorites.isChecked() \
                            or self.cB_itinerary.isChecked() \
                            or len(set(index.row() for index in self.tW_tracks.selectedIndexes())) > 0:
                        flag = True
        except Exception:
            pass

        try:  # Qt6
            self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setEnabled(flag)
        except AttributeError:  # Qt5
            self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setEnabled(flag)
