# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OsmAnd bridge
                                 A QGIS plugin
 Import tracks, favorites, itinerary and AV notes from OsmAnd
 Generated by Plugin Builder: https://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-04-10
        git sha              : $Format:%H$
        copyright            : (C) 2022-2026 by Sylvain Théry - UMR 5281 ART-Dev
        email                : sylvain.thery@cnrs.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path
import socket
from configparser import ConfigParser
from datetime import datetime

from qgis import processing
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant, QUrl, Qt, QLocale

from qgis.PyQt.QtGui import QIcon, QGuiApplication, QDesktopServices
from qgis.PyQt.QtWidgets import QAction, QProgressBar, QApplication
from qgis._core import QgsApplication
from qgis.core import QgsWkbTypes, QgsField, QgsMessageLog, Qgis, QgsProject, QgsFields, QgsRasterLayer, \
    QgsRectangle, QgsCoordinateReferenceSystem, QgsSettings

from .OsmAnd_bridge_import_dialog import OsmAndBridgeImportDialog
from .OsmAnd_bridge_import_process import import_gpx_track_file, import_avnotes, move_to_group
from .OsmAnd_bridge_geopackage_management import create_empty_gpkg_layer
from .OsmAnd_bridge_settings_management import msgbox_setting

# from qgis.utils import showPluginHelp


class OsmAndBridge:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor."""

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # Save reference to the plugin name and help website

        self.help_url_website = "https://osmand-bridge.readthedocs.io/"
        self.help_version = 'latest'
        self.help_languages = ('en', 'es', 'it', 'ja', 'pt', 'fi', 'fr')

        # print version number in console and log panel
        config = ConfigParser()
        config.read(f'{self.plugin_dir}/metadata.txt')
        self.plugin_name = config.get('general', 'name')
        print(f"{self.plugin_name} {config.get('general', 'version')} loaded")
        QgsMessageLog.logMessage(f"{self.plugin_name} {config.get('general', 'version')} loaded",
                                 self.plugin_name, level=Qgis.Info)

        self.debug = False
        if self.debug:
            QgsMessageLog.logMessage("Trying to run into debug mode", self.plugin_name, level=Qgis.Info)
            try:
                import pydevd_pycharm
                try:
                    pydevd_pycharm.settrace('localhost', port=53100, stdoutToServer=True,
                                            stderrToServer=True, suspend=False)
                    QgsMessageLog.logMessage("Debugging into pyCharm", self.plugin_name, level=Qgis.Info)
                except Exception:
                    QgsMessageLog.logMessage("No python remote debug server", self.plugin_name, level=Qgis.Warning)
            except ImportError:
                QgsMessageLog.logMessage("pydedv_pycharm package not found", self.plugin_name, level=Qgis.Critical)

        # Save reference to the QGIS interface
        self.iface = iface
        # Save reference to the QGIS project instance
        self.project = QgsProject.instance()

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'OsmAnd_bridge_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&OsmAnd bridge')

        self.first_start = None

        # Add a toolbar
        self.toolbar = self.iface.addToolBar(u'OsmAnd bridge')
        self.toolbar.setObjectName(u'OsmAnd bridge')

        # delai for map tip display
        QgsSettings().setValue('qgis/mapTipsDelay', 500)

        self.PARAM_FILE = f"{os.path.dirname(__file__)}/settings.json"

    def tr(self, message):
        return QCoreApplication.translate('OsmAndBridge', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = f"{self.plugin_dir}/OsmAnd_logo.png"

        # Create menu with icon using pluginMenu().addMenu()
        # This method allows having an icon on the menu name itself in the Plugin menu
        menu_icon = QIcon(icon_path)
        self.menu_obj = self.iface.pluginMenu().addMenu(menu_icon, self.tr(u'&OsmAnd bridge'))

        # 'Import' entry
        import_action = QAction(QIcon(icon_path),
                                self.tr(u"Import tracks, favorites, itinerary and AV notes"),
                                self.iface.mainWindow())
        import_action.triggered.connect(self.run)
        self.menu_obj.addAction(import_action)
        self.toolbar.addAction(import_action)
        self.actions.append(import_action)

        # 'Reset settings' entry
        reset_action = QAction(QgsApplication.getThemeIcon("console/iconSettingsConsole.svg"),
                               self.tr(u"Reset saved settings"),
                               self.iface.mainWindow())
        reset_action.triggered.connect(self.remove_config_file)
        self.menu_obj.addAction(reset_action)
        self.actions.append(reset_action)

        # 'Help' entry
        # TODO
        # help_action = QAction(QgsApplication.getThemeIcon("mActionHelpContents.svg"),
        #                       self.tr(u"Help"),
        #                       self.iface.mainWindow())
        # help_action.triggered.connect(self.show_help_website)
        # self.menu_obj.addAction(help_action)
        # self.toolbar.addAction(help_action)
        # self.actions.append(help_action)
        #
        # help_plugin_osmand_bridge_menu = QAction(QIcon(icon_path), self.plugin_name, self.iface.mainWindow())
        # self.iface.pluginHelpMenu().addAction(help_plugin_osmand_bridge_menu)
        # help_plugin_osmand_bridge_menu.triggered.connect(self.show_help_website)
        # self.actions.append(help_plugin_osmand_bridge_menu)

        self.first_start = True

    def show_help_website(self):
        """Show the help screen."""
        # BUG FIX #5 : utilisation correcte de l'URL avec la locale
        locale = QgsSettings().value("locale/userLocale", QLocale().name())
        locale = locale[0:2]
        if locale not in self.help_languages:
            locale = 'en'
        url = QUrl(f"{self.help_url_website}{locale}/{self.help_version}/")
        QDesktopServices.openUrl(url)

    def remove_config_file(self):
        """Remove config file."""
        try:
            os.remove(self.PARAM_FILE)
        except OSError:
            pass

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # Remove menu created with pluginMenu().addMenu()
        if hasattr(self, 'menu_obj') and self.menu_obj:
            self.iface.pluginMenu().removeAction(self.menu_obj.menuAction())
            self.menu_obj.deleteLater()
            self.menu_obj = None

        for action in self.actions:
            self.iface.removeToolBarIcon(action)
            self.iface.pluginHelpMenu().removeAction(action)
        del self.toolbar

    def run(self):
        """Launch import dialog and import OsmAnd data if found."""

        setting_name = "hide_unstable_warning_message"
        title = self.tr("Warning")
        message = self.tr("This plugin uses experimental libraries to access devices (MTP protocol). "
                          "\nIn rare cases, it can cause Qgis to crash.")
        msgbox_setting(self, setting_name, title, message)

        self.dlg_import = OsmAndBridgeImportDialog()

        # On Windows, comtypes may have just been installed: show message and stop
        if self.dlg_import._needs_restart:
            from qgis.PyQt.QtWidgets import QMessageBox
            msg = QMessageBox()
            msg.setWindowTitle(self.tr("OsmAnd bridge - restart required"))
            msg.setText(self.tr(
                "The <b>comtypes</b> library has been installed.<br>"
                "Please restart QGIS for the change to take effect."
            ))
            try:
                msg.setStandardButtons(QMessageBox.StandardButton.Ok)
            except AttributeError:
                msg.setStandardButtons(QMessageBox.Ok)
            msg.exec()
            return

        # show the dialog
        self.dlg_import.show()
        # Run the dialog event loop
        result = self.dlg_import.exec()
        QGuiApplication.restoreOverrideCursor()
        # See if OK was pressed
        if result:
            # define empty extent that will be updated when adding layers
            self.extent = QgsRectangle()
            self.extent.setMinimal()

            # sets the project CRS
            self.crs = QgsCoordinateReferenceSystem.fromEpsgId(4326)
            self.project.setCrs(self.crs)

            # get time to generate gpkg name, and project name if not already set
            now = datetime.now().strftime("%Y%m%d-%Hh%Mm%Ss")

            # affect or get filename and save project before continuing
            if self.project.fileName() == '':
                qgis_project_filename = f'{self.dlg_import.QgsFW_dest_path.filePath()}/{now}_OsmAnd_bridge.qgz'
            else:
                qgis_project_filename = self.project.fileName()
            self.project.write(qgis_project_filename)

            self.osmand_root_path = self.dlg_import.QgsFW_osmand_root_path.filePath()
            self.dest_path = self.dlg_import.QgsFW_dest_path.filePath()
            self.dest_gpkg = f'{self.dlg_import.QgsFW_dest_path.filePath()}/{now}_OsmAnd_bridge.gpkg'

            # Create dest directory if not exists
            os.makedirs(os.path.dirname(f'{self.dlg_import.QgsFW_dest_path.filePath()}'), exist_ok=True)

            # Work around to create GPKG file (with an empty table that will be removed)
            # see https://gis.stackexchange.com/a/417950
            schema = QgsFields()
            schema.append(QgsField("bool_field", QVariant.Bool))
            create_empty_gpkg_layer(self.dest_gpkg, "temp_table", QgsWkbTypes.NoGeometry, '', schema)
            if not os.path.exists(os.path.dirname(self.dest_gpkg)):
                message = self.tr(f'Issue when trying to create destination geopackage file ({self.dest_gpkg})')
                QgsMessageLog.logMessage(message, self.plugin_name, level=Qgis.Critical)
                self.iface.messageBar().pushMessage(message, level=Qgis.Critical)
                return

            # Now dealing with AV notes
            if self.dlg_import.cB_AVnotes.isChecked():
                os.makedirs(f'{self.dlg_import.QgsFW_dest_path.filePath()}/avnotes', exist_ok=True)
                import_avnotes(self, f"{self.osmand_root_path}/avnotes/")

            # Now dealing with favorites gpx file
            if self.dlg_import.cB_favorites.isChecked():
                # BUG FIX #4 : le fichier favoris est dans favorites/favorites.gpx
                file = 'favorites/favorites.gpx'
                message = self.tr(f"Importing favorites ({file})")
                self.iface.messageBar().pushMessage(message, level=Qgis.Info)
                QgsMessageLog.logMessage(message, self.plugin_name, level=Qgis.Info)
                result = import_gpx_track_file(self, f'{self.osmand_root_path}/{file}')
                if not result:
                    self.iface.messageBar().clearWidgets()
                    message = self.tr(f'Something went wrong while importing favorites ({file})')
                    QgsMessageLog.logMessage(message, self.plugin_name, level=Qgis.Critical)
                    self.iface.messageBar().pushMessage(message, level=Qgis.Critical)
                    return
            self.iface.messageBar().clearWidgets()

            # Now dealing with itinerary gpx file
            if self.dlg_import.cB_itinerary.isChecked():
                file = 'itinerary.gpx'
                message = self.tr(f"Importing itinerary ({file})")
                self.iface.messageBar().pushMessage(message, level=Qgis.Info)
                QgsMessageLog.logMessage(message, self.plugin_name, level=Qgis.Info)
                result = import_gpx_track_file(self, f'{self.osmand_root_path}/{file}')
                if not result:
                    self.iface.messageBar().clearWidgets()
                    message = self.tr(f'Something went wrong while importing itinerary ({file})')
                    QgsMessageLog.logMessage(message, self.plugin_name, level=Qgis.Critical)
                    self.iface.messageBar().pushMessage(message, level=Qgis.Critical)
                    return
            self.iface.messageBar().clearWidgets()

            # Now dealing with selected gpx tracks files
            i = 0
            for currentQTableWidgetItem in self.dlg_import.tW_tracks.selectedItems():
                if currentQTableWidgetItem.column() == 0:
                    i += 1
            progressMessageBar = self.iface.messageBar().createMessage(self.tr("Importing track files..."))
            progress = QProgressBar()
            progress.setMaximum(10)
            try:  # Qt6 — enums namespaced
                progress.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
            except AttributeError:  # Qt5
                progress.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
            progressMessageBar.layout().addWidget(progress)
            self.iface.messageBar().pushWidget(progressMessageBar, Qgis.Info)

            j = 0
            for currentQTableWidgetItem in self.dlg_import.tW_tracks.selectedItems():
                if currentQTableWidgetItem.column() == 0:
                    gpx_file = f'{self.osmand_root_path}/tracks/rec/{currentQTableWidgetItem.text()}'
                    result = import_gpx_track_file(self, gpx_file)
                    j += 1
                    progress.setValue(j)
                    if not result:
                        self.iface.messageBar().clearWidgets()
                        message = self.tr(f'Something went wrong while importing {currentQTableWidgetItem.text()}')
                        QgsMessageLog.logMessage(message, self.plugin_name, level=Qgis.Critical)
                        self.iface.messageBar().pushMessage(message, level=Qgis.Critical)
                        return
            self.iface.messageBar().clearWidgets()

            # Now dealing with map background
            try:
                socket.create_connection(("tile.openstreetmap.org", 443))
                tms = 'type=xyz&url=https://tile.openstreetmap.org/{z}/{x}/{y}.png&zmax=19&zmin=0'
                layer = QgsRasterLayer(tms, 'OpenStreetMap', 'wms')
                QgsProject.instance().addMapLayer(layer)
                move_to_group(layer, self.tr('Map background'))
            except Exception:
                message = self.tr('No internet connection. Unable to load OSM tile background')
                QgsMessageLog.logMessage(message, self.plugin_name, level=Qgis.Warning)
                self.iface.messageBar().pushMessage(message, level=Qgis.Warning)

            # set map canvas extent
            QApplication.instance().processEvents()
            self.iface.mapCanvas().zoomToFeatureExtent(self.extent)
            self.iface.mapCanvas().refresh()

            # if present, remove the temp_layer previously created to generate destination gpkg
            try:
                processing.run("native:spatialiteexecutesql",
                               {'DATABASE': f'{self.dest_gpkg}|layername=temp_table', 'SQL': 'drop table temp_table'})
            except Exception:
                pass

            # Show success message when finished
            self.iface.messageBar().clearWidgets()
            message = "♪♫ This is the End, my only friend, the End ♫♪ "
            QgsMessageLog.logMessage(message, self.plugin_name, level=Qgis.Success)
            self.iface.messageBar().pushMessage(message, level=Qgis.Success, duration=0)

            # close dialog and save project
            self.dlg_import.close()
            try:
                self.project.write(qgis_project_filename)
            except Exception:
                pass
