from enum import IntFlag

from . import _1F001332_1A57_4934_BE31_AFFC99F4EE0A_0_1_0 as __wrapper_module__
from . _1F001332_1A57_4934_BE31_AFFC99F4EE0A_0_1_0 import (
    WSTRING, _wireSAFEARRAY, tagCABSTRBLOB,
    IEnumPortableDeviceObjectIDs, _wireSAFEARR_HAVEIID,
    _wireSAFEARR_BRECORD, tagSYSKIND, tagSTATSTG, tagCALPWSTR,
    IPortableDeviceCapabilities, _SHORT_SIZEDARR, IPortableDevice,
    IEnumSTATSTG, IPortableDeviceServiceMethodCallback, tagIDLDESC,
    tagVARDESC, ULONG_PTR, _wireVARIANT,
    IPortableDeviceDispatchFactory, CoClass,
    __MIDL_IOleAutomationTypes_0004, IPortableDeviceContent,
    wirePSAFEARRAY, tagCABOOL, _wireSAFEARR_VARIANT,
    PortableDeviceFTM, IPortableDeviceManager, IUnknown, tagCAUL,
    PortableDeviceService, _wireBRECORD,
    __MIDL_IOleAutomationTypes_0001, tagCAH, VARIANT_BOOL,
    tagARRAYDESC, _lcid, dispid, tagCACLIPDATA, tagCAC, SCODE,
    IRecordInfo, tagTLIBATTR, tagCADBL, tagCAFLT,
    PortableDeviceWebControl, _FILETIME, IPortableDeviceContent2,
    _LARGE_INTEGER, tagELEMDESC, ITypeLib, ISequentialStream, VARIANT,
    IDispatch, PortableDeviceManager, tagBLOB, IPortableDeviceValues,
    _check_version, tagFUNCDESC, IPortableDeviceWebControl,
    _wireSAFEARRAY_UNION, PortableDevice, tagCAL, tagTYPEDESC,
    tagFUNCKIND, _wireSAFEARR_DISPATCH, IPortableDeviceResources,
    IPortableDeviceProperties, HRESULT, tagPARAMDESC, tagCASCODE,
    typelib_path, tagBSTRBLOB, tagCAUI, IStorage, tagCAUB, tagCABSTR,
    ITypeInfo, _tagpropertykey, tagCACLSID,
    IPortableDeviceServiceCapabilities, _ULARGE_INTEGER,
    IPropertyStore, tagCLIPDATA, __MIDL_IOleAutomationTypes_0005,
    __MIDL_IOleAutomationTypes_0006, IPortableDeviceEventCallback,
    tagCAPROPVARIANT, COMMETHOD, tagCALLCONV, tagPARAMDESCEX, Library,
    tagVersionedStream, IPortableDeviceKeyCollection,
    IPortableDeviceValuesCollection, tagTYPEATTR, tagCAI,
    _HYPER_SIZEDARR, STRING, IStream, tagCACY, tagCADATE, tagVARKIND,
    _wireSAFEARR_BSTR, _wireSAFEARR_UNKNOWN, tagCAFILETIME, tagRemSNB,
    PortableDeviceServiceFTM, BSTR, tagTYPEKIND,
    IPortableDeviceService, IPortableDevicePropVariantCollection,
    DECIMAL, _BYTE_SIZEDARR,
    __MIDL___MIDL_itf_PortableDeviceApi_0001_0000_0001,
    IPortableDeviceServiceMethods, ITypeComp, helpstring,
    tag_inner_PROPVARIANT, DWORD, wireSNB, tagDESCKIND, tagCALPSTR,
    tagINVOKEKIND, tagSAFEARRAYBOUND, GUID, _LONG_SIZEDARR,
    PortableDeviceDispatchFactory, _FLAGGED_WORD_BLOB, tagCAUH
)


__all__ = [
    '_wireSAFEARRAY', 'tagCABSTRBLOB', '_wireSAFEARR_HAVEIID',
    '_wireSAFEARR_BRECORD', 'IPortableDeviceCapabilities',
    'IPortableDeviceDispatchFactory', 'IPortableDeviceContent',
    'wirePSAFEARRAY', 'tagCABOOL', 'IPortableDeviceManager',
    'tagCAUL', 'PortableDeviceService', '_wireBRECORD',
    '__MIDL_IOleAutomationTypes_0001', 'tagCACLIPDATA', 'tagCAC',
    'tagCAFLT', 'PortableDeviceManager', 'IPortableDeviceValues',
    '_wireSAFEARRAY_UNION', '_wireSAFEARR_DISPATCH',
    'IPortableDeviceProperties', 'tagCASCODE', 'tagCAUI', 'IStorage',
    'IPropertyStore', 'tagCLIPDATA',
    '__MIDL_IOleAutomationTypes_0005', 'IPortableDeviceEventCallback',
    'Library', 'IPortableDeviceValuesCollection', 'tagCAI', 'IStream',
    'tagCACY', 'IPortableDeviceService', '_BYTE_SIZEDARR',
    '__MIDL___MIDL_itf_PortableDeviceApi_0001_0000_0001',
    'IPortableDeviceServiceMethods', 'tag_inner_PROPVARIANT',
    '_LONG_SIZEDARR', 'PortableDeviceDispatchFactory',
    '_FLAGGED_WORD_BLOB', 'tagCAUH', 'IEnumPortableDeviceObjectIDs',
    'tagSTATSTG', 'tagCALPWSTR', '_SHORT_SIZEDARR', 'IPortableDevice',
    'IEnumSTATSTG', 'IPortableDeviceServiceMethodCallback',
    '_wireVARIANT', '__MIDL_IOleAutomationTypes_0004',
    '_wireSAFEARR_VARIANT', 'PortableDeviceFTM', 'tagCAH', 'tagCADBL',
    'PortableDeviceWebControl', 'IPortableDeviceContent2', 'tagBLOB',
    'IPortableDeviceWebControl', 'PortableDevice', 'tagCAL',
    'IPortableDeviceResources', 'typelib_path', 'tagBSTRBLOB',
    'tagCAUB', 'tagCABSTR', '_tagpropertykey', 'tagCACLSID',
    'IPortableDeviceServiceCapabilities',
    '__MIDL_IOleAutomationTypes_0006', 'tagCAPROPVARIANT',
    'tagVersionedStream', 'IPortableDeviceKeyCollection',
    '_HYPER_SIZEDARR', 'tagCADATE', '_wireSAFEARR_BSTR',
    '_wireSAFEARR_UNKNOWN', 'tagCAFILETIME', 'tagRemSNB',
    'PortableDeviceServiceFTM',
    'IPortableDevicePropVariantCollection', 'wireSNB', 'tagCALPSTR'
]

