"""
mtp_access_windows.py
=====================
MTP device access on Windows via the native WPD (Windows Portable Devices) COM API.
Uses comtypes.client.GetModule to load interfaces from portabledeviceapi.dll,
with raw vtable calls for methods whose [out] parameters comtypes mishandles.

Public API (same as mtp_access_kio_gvfs.MTPClient):
    client = MTPClient()
    client.list_devices()                           -> ['Pixel 9']
    client.get_display_name('Pixel 9')              -> 'Pixel 9'
    client.list_folder('Pixel 9', '')               -> ['Internal storage']
    client.list_folder('Pixel 9', 'Internal storage/DCIM') -> [...]
    client.copy_from_device_to_exact('Pixel 9', 'Internal storage/...', r'C:\\tmp\\...')
"""

import ctypes
from ctypes import byref, c_ulong, c_wchar_p
from pathlib import Path

import comtypes
import comtypes.client
from comtypes import GUID, COMError

# ---------------------------------------------------------------------------
# Load WPD type library — comtypes generates interface wrappers automatically
# ---------------------------------------------------------------------------
_wpd = comtypes.client.GetModule(r"C:\Windows\System32\portabledeviceapi.dll")
_wpd_types = comtypes.client.GetModule(r"C:\Windows\System32\portabledevicetypes.dll")

IPortableDeviceManager = _wpd.IPortableDeviceManager
IPortableDevice = _wpd.IPortableDevice
IPortableDeviceContent = _wpd.IPortableDeviceContent
IPortableDeviceProperties = _wpd.IPortableDeviceProperties
IPortableDeviceValues = _wpd.IPortableDeviceValues

# ---------------------------------------------------------------------------
# CLSIDs
# ---------------------------------------------------------------------------
CLSID_PortableDeviceManager = GUID("{0AF10CEC-2ECD-4B92-9581-34F6AE0637F3}")
CLSID_PortableDevice = GUID("{728A21C5-3D9E-48D7-9810-864848F0F404}")
CLSID_PortableDeviceValues = GUID("{0C15D503-D017-47CE-9016-7B3F978721CC}")

# ---------------------------------------------------------------------------
# WPD constants
# ---------------------------------------------------------------------------
WPD_DEVICE_OBJECT_ID = "DEVICE"
_FMTID_OBJECT = GUID("{EF6B490D-5CD8-437A-AFFC-DA8B60EE4A3C}")
WPD_OBJECT_NAME_PID = 4
WPD_OBJECT_CONTENT_TYPE_PID = 7
WPD_CONTENT_TYPE_FOLDER = GUID("{27E2E392-A111-48E0-AB0C-E17705A05F85}")
WPD_CONTENT_TYPE_FUNCTIONAL = GUID("{99ED0160-17FF-4C44-9D98-1D7A6F941921}")
_FMTID_RESOURCE = GUID("{E81E79BE-34F0-41BF-B53F-F1A06AE87842}")
WPD_RESOURCE_DEFAULT_PID = 0
STGM_READ = 0x00000000
_CHUNK = 256 * 1024  # 256 KB


# ---------------------------------------------------------------------------
# PROPERTYKEY — use the type generated by comtypes from the typelib
# ---------------------------------------------------------------------------
def _find_pk_type(mod):
    for name in ('_tagpropertykey', 'tagPROPERTYKEY', 'PROPERTYKEY', '_PROPERTYKEY'):
        t = getattr(mod, name, None)
        if t is not None:
            return t

    class _PK(ctypes.Structure):
        _fields_ = [("fmtid", GUID), ("pid", c_ulong)]
    return _PK


_PK = _find_pk_type(_wpd)


def _pk(fmtid, pid):
    k = _PK()
    k.fmtid = fmtid
    k.pid = pid
    return k


# ---------------------------------------------------------------------------
# GUID value comparison — ctypes.Structure has no __eq__
# ---------------------------------------------------------------------------
def _guid_eq(a, b):
    try:
        return bytes(a) == bytes(b)
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Vtable helper
# ---------------------------------------------------------------------------
def _vtbl_fn(obj_addr, slot, restype, *argtypes):
    """Return a callable WINFUNCTYPE for vtable slot *slot* of COM object at *obj_addr*."""
    vtbl = ctypes.cast(obj_addr, ctypes.POINTER(ctypes.c_void_p))[0]
    fn = ctypes.cast(ctypes.c_void_p(
               ctypes.cast(vtbl, ctypes.POINTER(ctypes.c_void_p))[slot]),
               ctypes.c_void_p).value
    return ctypes.WINFUNCTYPE(restype, ctypes.c_void_p, *argtypes)(fn)


# ---------------------------------------------------------------------------
# IPortableDeviceManager — GetDevices and GetDeviceFriendlyName via vtable
# (nullable LPWSTR* params that comtypes cannot marshal)
# Vtable after IUnknown (0=QI,1=AddRef,2=Release):
# 3=GetDevices, 4=RefreshDeviceList, 5=GetDeviceFriendlyName, ...
# ---------------------------------------------------------------------------
def _list_device_ids(mgr) -> list:
    addr = ctypes.cast(mgr, ctypes.c_void_p).value
    fn = _vtbl_fn(addr, 3, ctypes.HRESULT, ctypes.c_void_p, ctypes.POINTER(c_ulong))
    count = c_ulong(0)
    fn(addr, None, byref(count))
    if count.value == 0:
        return []
    arr = (c_wchar_p * count.value)()
    fn(addr, ctypes.cast(arr, ctypes.c_void_p), byref(count))
    return [arr[i] for i in range(count.value)]


def _get_friendly_name(mgr, device_id: str) -> str:
    addr = ctypes.cast(mgr, ctypes.c_void_p).value
    fn = _vtbl_fn(addr, 5, ctypes.HRESULT, c_wchar_p, ctypes.c_void_p, ctypes.POINTER(c_ulong))
    length = c_ulong(0)
    fn(addr, device_id, None, byref(length))
    if length.value == 0:
        return device_id
    buf = (ctypes.c_wchar * length.value)()
    fn(addr, device_id, ctypes.cast(buf, ctypes.c_void_p), byref(length))
    return buf.value or device_id


# ---------------------------------------------------------------------------
# IPortableDeviceContent helpers via vtable
# Vtable after IUnknown:
#   3=EnumObjects, 4=Properties, 5=Transfer, 6=CreateObjectWithPropertiesOnly
# ---------------------------------------------------------------------------
def _content_enum_objects(content_addr, parent_id: str):
    """Call EnumObjects and return raw enum pointer address."""
    fn = _vtbl_fn(content_addr, 3, ctypes.HRESULT, c_ulong, c_wchar_p,
                  ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p))
    out_ptr = ctypes.c_void_p(0)
    hr = fn(content_addr, 0, parent_id, None, byref(out_ptr))
    if hr != 0:
        raise COMError(hr, "EnumObjects failed", ())
    return out_ptr.value


def _content_transfer(content_addr):
    """Call Transfer() and return raw IPortableDeviceResources pointer address."""
    fn = _vtbl_fn(content_addr, 5, ctypes.HRESULT, ctypes.POINTER(ctypes.c_void_p))
    out_ptr = ctypes.c_void_p(0)
    hr = fn(content_addr, byref(out_ptr))
    if hr != 0:
        raise COMError(hr, "Transfer() failed", ())
    return out_ptr.value


# ---------------------------------------------------------------------------
# IEnumPortableDeviceObjectIDs.Next via vtable
# Vtable after IUnknown: 3=Next, 4=Skip, 5=Reset, 6=Clone, 7=Cancel
# ---------------------------------------------------------------------------
def _enum_next(enum_addr, batch=16) -> list:
    """Drain an IEnumPortableDeviceObjectIDs and return all object ID strings."""
    fn = _vtbl_fn(enum_addr, 3, ctypes.HRESULT, c_ulong, ctypes.c_void_p, ctypes.POINTER(c_ulong))
    ids = []
    while True:
        buf = (c_wchar_p * batch)()
        fetched = c_ulong(0)
        hr = fn(enum_addr, batch, ctypes.cast(buf, ctypes.c_void_p), byref(fetched))
        n = fetched.value
        for i in range(n):
            if buf[i]:
                ids.append(buf[i])
        if hr != 0 or n < batch:  # S_FALSE or last batch
            break
    return ids


# ---------------------------------------------------------------------------
# IPortableDeviceResources.GetStream via vtable
# Vtable after IUnknown:
#   3=GetSupportedResources, 4=GetResourceAttributes, 5=GetStream, ...
# Signature: GetStream(LPCWSTR objID, REFPROPERTYKEY key, DWORD mode,
#                      DWORD* optChunk, IStream** ppStream)
# ---------------------------------------------------------------------------
def _resources_get_stream(res_addr, oid: str):
    """Open a read stream for *oid*. Returns (stream_addr, chunk_size)."""
    pk = _pk(_FMTID_RESOURCE, WPD_RESOURCE_DEFAULT_PID)
    optimal_chunk = c_ulong(0)
    stream_ptr = ctypes.c_void_p(0)
    fn = _vtbl_fn(res_addr, 5, ctypes.HRESULT,
                  c_wchar_p,              # pszObjectID
                  ctypes.c_void_p,                 # pKey (REFPROPERTYKEY)
                  c_ulong,                         # dwMode
                  ctypes.POINTER(c_ulong),         # pdwOptimalBufferSize [in,out]
                  ctypes.POINTER(ctypes.c_void_p)  # ppStream [out]
                  )
    hr = fn(res_addr, oid,
            ctypes.cast(ctypes.addressof(pk), ctypes.c_void_p),
            STGM_READ,
            byref(optimal_chunk),
            byref(stream_ptr))
    if hr != 0:
        raise COMError(hr, f"GetStream hr=0x{hr & 0xFFFFFFFF:08X}", ())
    chunk = optimal_chunk.value if optimal_chunk.value > 0 else _CHUNK
    return stream_ptr.value, chunk


# ---------------------------------------------------------------------------
# ISequentialStream.Read via vtable (slot 3 after IUnknown)
# ---------------------------------------------------------------------------
def _com_release(addr):
    """Call IUnknown::Release() (vtable slot 2) on a raw COM pointer address."""
    if addr:
        _vtbl_fn(addr, 2, ctypes.c_ulong)(addr)


def _stream_read_to_file(stream_addr, chunk_size, dst_file: Path):
    """Read stream into dst_file, then Release() the stream."""
    fn = _vtbl_fn(stream_addr, 3, ctypes.HRESULT,
                  ctypes.c_void_p, c_ulong, ctypes.POINTER(c_ulong))
    buf = (ctypes.c_char * chunk_size)()
    dst_file.parent.mkdir(parents=True, exist_ok=True)
    try:
        with open(dst_file, 'wb') as fh:
            while True:
                n_read = c_ulong(0)
                hr = fn(stream_addr,
                        ctypes.cast(buf, ctypes.c_void_p),
                        chunk_size,
                        byref(n_read))
                n = n_read.value
                if n > 0:
                    fh.write(buf[:n])
                if hr != 0 or n == 0:
                    break
    finally:
        _com_release(stream_addr)


# ---------------------------------------------------------------------------
# IPortableDeviceProperties helpers
# Comtypes-generated GetValues / GetStringValue / GetGuidValue work correctly
# as long as we pass the right pointer type for PROPERTYKEY.
# ---------------------------------------------------------------------------
def _obj_name(properties, oid: str) -> str:
    try:
        pk = _pk(_FMTID_OBJECT, WPD_OBJECT_NAME_PID)
        return properties.GetValues(oid, None).GetStringValue(ctypes.pointer(pk)) or oid
    except COMError:
        return oid


def _obj_is_folder(properties, oid: str) -> bool:
    try:
        pk = _pk(_FMTID_OBJECT, WPD_OBJECT_CONTENT_TYPE_PID)
        g = properties.GetValues(oid, None).GetGuidValue(ctypes.pointer(pk))
        return _guid_eq(g, WPD_CONTENT_TYPE_FOLDER) or _guid_eq(g, WPD_CONTENT_TYPE_FUNCTIONAL)
    except COMError:
        return False


# ---------------------------------------------------------------------------
# _WPDDevice  — wraps one open device connection
# ---------------------------------------------------------------------------
class _WPDDevice:
    def __init__(self, device_id: str, friendly_name: str):
        self.device_id = device_id
        self.friendly_name = friendly_name
        # Open device
        self._device = comtypes.client.CreateObject(CLSID_PortableDevice,
                                                    interface=IPortableDevice)
        client_info = comtypes.client.CreateObject(CLSID_PortableDeviceValues,
                                                   interface=IPortableDeviceValues)
        self._device.Open(device_id, client_info)
        self._content = self._device.Content()
        # Raw content pointer for vtable calls
        self._content_addr = ctypes.cast(self._content, ctypes.c_void_p).value
        # NOTE: _properties is NOT stored persistently.
        # Keeping IPortableDeviceProperties open while calling GetStream causes
        # ERROR_BUSY (0x800700AA). We acquire it only during enumeration and
        # release it (by letting the local variable go out of scope) before
        # any download.

    def close(self):
        try:
            if self._device:
                self._device.Close()
        except Exception:
            pass
        self._device = self._content = None

    # ------------------------------------------------------------------
    # Object tree
    # ------------------------------------------------------------------

    def _children(self, parent_id: str) -> list:
        """Return list of (oid, name, is_folder) for direct children.

        IPortableDeviceProperties is acquired locally and released
        (goes out of scope) before this method returns, so it does not
        hold the device busy during subsequent GetStream calls.
        """
        enum_addr = _content_enum_objects(self._content_addr, parent_id)
        oids = _enum_next(enum_addr)
        properties = self._content.Properties()  # local — released on return
        result = []
        for oid in oids:
            name = _obj_name(properties, oid)
            is_folder = _obj_is_folder(properties, oid)
            result.append((oid, name, is_folder))
        del properties  # explicitly release before any download
        return result

    def _resolve(self, path: str):
        """Resolve slash-separated path to (oid, is_folder). Returns None if not found."""
        if not path:
            return WPD_DEVICE_OBJECT_ID, True
        parts = [p for p in path.replace('\\', '/').split('/') if p]
        current_id = WPD_DEVICE_OBJECT_ID
        for part in parts:
            found = None
            for oid, name, is_folder in self._children(current_id):
                if name.lower() == part.lower():
                    found = (oid, is_folder)
                    break
            if found is None:
                return None
            current_id, last_is_folder = found
        return current_id, last_is_folder

    def list_folder(self, path: str) -> list:
        res = self._resolve(path)
        if res is None or not res[1]:
            return []
        return [name for _, name, _ in self._children(res[0])]

    # ------------------------------------------------------------------
    # Download
    # ------------------------------------------------------------------

    def _download(self, oid: str, dst: Path):
        """Download one file from the device.

        Each download uses a fresh IPortableDeviceResources (Transfer()) and
        releases both the stream and the resources after use, so the device
        is not held busy for subsequent downloads.
        """
        res_addr = _content_transfer(self._content_addr)
        try:
            stream_addr, chunk = _resources_get_stream(res_addr, oid)
            _stream_read_to_file(stream_addr, chunk, dst)
            # stream is released inside _stream_read_to_file
        finally:
            _com_release(res_addr)

    def _copy_tree(self, oid: str, is_folder: bool, dst: Path):
        """Recursively copy object *oid* to local *dst*."""
        if is_folder:
            dst.mkdir(parents=True, exist_ok=True)
            for child_oid, child_name, child_is_folder in self._children(oid):
                self._copy_tree(child_oid, child_is_folder, dst / child_name)
        else:
            self._download(oid, dst)

    def copy_subtree(self, src_path: str, dst_exact: Path):
        res = self._resolve(src_path)
        if res is None:
            raise FileNotFoundError(f"Not found on {self.friendly_name!r}: {src_path!r}")
        oid, is_folder = res
        if is_folder:
            dst_exact.mkdir(parents=True, exist_ok=True)
            for child_oid, child_name, child_is_folder in self._children(oid):
                self._copy_tree(child_oid, child_is_folder, dst_exact / child_name)
        else:
            self._download(oid, dst_exact)


# ---------------------------------------------------------------------------
# MTPClient — public API
# ---------------------------------------------------------------------------
class MTPClient:
    """Windows WPD MTP client. Same public API as mtp_access_kio_gvfs.MTPClient."""

    def __init__(self):
        self.backend = 'wpd'
        self._registry = {}  # friendly_name -> (device_id, _WPDDevice|None)
        mgr = comtypes.client.CreateObject(CLSID_PortableDeviceManager,
                                           interface=IPortableDeviceManager)
        for dev_id in _list_device_ids(mgr):
            name = _get_friendly_name(mgr, dev_id)
            self._registry[name] = (dev_id, None)
        if not self._registry:
            raise RuntimeError("No WPD/MTP devices found. "
                               "Connect and unlock the device.")

    def _dev(self, name: str) -> _WPDDevice:
        if name not in self._registry:
            raise KeyError(f"Unknown device: {name!r}")
        dev_id, wpd = self._registry[name]
        if wpd is None:
            wpd = _WPDDevice(dev_id, name)
            self._registry[name] = (dev_id, wpd)
        return wpd

    def list_devices(self) -> list:
        return list(self._registry.keys())

    def get_display_name(self, device: str) -> str:
        return device

    def list_root_folders(self) -> dict:
        return {n: self.list_folder(n, '') for n in self._registry}

    def list_folder(self, device: str, path: str) -> list:
        return self._dev(device).list_folder(path)

    def copy_from_device(self, device: str, src_path: str, dst_local: str):
        self.copy_from_device_to_exact(
            device, src_path, str(Path(dst_local) / Path(src_path).name))

    def copy_from_device_to_exact(self, device: str, src_path: str, dst_exact: str):
        self._dev(device).copy_subtree(src_path, Path(dst_exact))


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------
if __name__ == '__main__':
    client = MTPClient()
    print("Devices:", client.list_devices())
    for dev, folders in client.list_root_folders().items():
        print(f" {dev}: {folders}")
